version: '3.4'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5.9'
    ports:
      - '2181:2181'
    volumes:
      - '.docker/zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'bitnami/kafka:3.0.0' # not zookeeper less image
    ports:
      - '9092'
    volumes:
      - '.docker/kafka1/data:/bitnami/kafka/data'
#      - 'kafka1_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:3.0.0'
    ports:
      - '9092'
    volumes:
      - '.docker/kafka2/data:/bitnami/kafka/data'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:3.0.0'
    ports:
      - '9092'
    volumes:
      - '.docker/kafka3/data:/bitnami/kafka/data'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#volumes:
#  kafka1_data:
#    driver: local
